title: MailWebhook Documentation
description: Documentation for MailWebhook
#theme: just-the-docs
remote_theme: pavelsg/just-the-docs

url: https://pavelsg.github.io/mailwebhook-docs

aux_links:
  Template Repository: https://github.com/pavelsg/just-the-docs-template

#plugins:
#  - jekyll-default-layout
